# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: /work/config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, 
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the 
# same biological sample).If the column "strandedness" is present (which is optional), 
# can be empty or has one of these values: none, yes or reverse. none is for unstranded 
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse` 
# which is referenced in STAR manual section 7, "Counting number of reads per gene".

units: /work/config/units.tsv

trimming:
  # skip trimming: false or true
  skip: false
  # the sequencing adapter
  adapter: ACGGATCGATCGATCGATCGAT

ref:
  # the STAR index
  index: "/ref/starIndex/hg38"
  # gtf file with transcripts
  annotation: "/ref/annotation/hg38.ncbiRefSeq.gtf"
  chromsizes: "/ref/annotation/hg38.chrom.sizes"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    treated-vs-untreated:
      - treated
      - untreated

params:
  star: ""
  cutadapt-se: ""
  cutadapt-pe: ""

star: "/install/STAR-2.7.7a/bin/Linux_x86_64/STAR"