import pandas as pd
from snakemake.utils import validate, min_version

##### set minimum snakemake version #####
min_version("5.1.2")


##### load config and sample sheets #####


configfile: "/work/config/config.yaml"


validate(config, schema="schemas/config.schema.yaml")

samples = pd.read_table(config["samples"]).set_index("sample", drop=False)
validate(samples, schema="schemas/samples.schema.yaml")
print(samples["sample"])

units = pd.read_table(config["units"], dtype=str).set_index(
    ["sample", "unit"], drop=False
)
units.index = units.index.set_levels(
    [i.astype(str) for i in units.index.levels]
)  # enforce str in index
validate(units, schema="schemas/units.schema.yaml")
print(units["unit"])

##### target rules #####


rule all:
    input:
        expand(
            [
                "/output/star/{sample}-{unit}/Aligned.out.bam",
                "/output/star/{sample}-{unit}/ReadsPerGene.out.tab",
                "/output/star/{sample}-{unit}.flagstat",
                "/output/qc/rseqc/{sample}-{unit}.junctionanno.junction.bed"
            ],
            sample = samples["sample"],
            unit = units["unit"]
        ),
        "/output/counts/raw_counts.tsv",
        "/output/qc/multiqc_report.html",


##### setup report #####


report: "report/workflow.rst"


##### load rules #####


include: "rules/common.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/counts.smk"
include: "rules/qc.smk"
include: "rules/post-analysis.smk"
