samples: samples.tsv
units: units.tsv

trimming:
  # skip trimming: false or true
  skip: false
  # the sequencing adapter
  adapter: ACGGATCGATCGATCGATCGAT

ref:
  # the STAR index
  index: "data/ref/index"
  # gtf file with transcripts
  annotation: "data/ref/annotation.gtf"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    SY5Y_parental:
      - SY5Y_parental_control
      - SY5Y_parental_24h_PB

params:
  star: ""
  cutadapt-se: ""
  cutadapt-pe: ""
